server:
  port: 9001

spring:
  output:
    ansi:
      enabled: ALWAYS

  application:
    name: users-app

  datasource:
    driver-class-name: org.h2.Driver
    username: a
    password: a
    url: "jdbc:h2:mem:usersapp;DB_CLOSE_ON_EXIT=false;NON_KEYWORDS=user"
      # Workaround. El servicio trata con una tabla SQL llamada "USER" que es palabra reservada de H2 (¿o SQL?). Se
           # pueden prevenir errores en los archivos schema y data, pero no en las sentencias hechas por JPA.Próximos
           # microservicios tendrán una tabla de usuarios con otro nombre.

    initialization-mode: always
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}